#!/bin/bash

i=1
for f in $(ls src/main/resources/db/migration/*.sql | sort); do
        filename=$(basename "$f")
        name="${filename#*__}"  # remove existing version prefix if any
        echo "Renaming $filename -> V${i}__${name}"
        mv -- "$f" "src/main/resources/db/migration/V${i}__${name}"
        ((i++))
    done

    echo "All migration files renamed successfully."