@startuml usecase

left to right direction

actor Guest
actor Student
actor Teacher
actor Admin

rectangle "Enrollment and Scheduling System" {

    usecase "authenticate"

    rectangle "Course" {
        usecase "search" as course_search
        usecase "view" as course_view
        usecase "manage" as course_manage
    }
    
    rectangle "Enrollment" {
        usecase "enroll" as enrollment_enroll /'meaning to enroll'/
        usecase "search" as enrollment_search
        usecase "view" as enrollment_view
        usecase "drop" as enrollment_drop
    }
    
    rectangle "Classroom" {
        usecase "search" as classroom_search
        usecase "view" as classroom_view
        usecase "administrate" as classroom_administrate

        rectangle "Schedule" {
            usecase "search" as schedule_search
            usecase "view" as schedule_view
            usecase "administrate" as schedule_administrate
        }
    }
}

' ====================
Guest --> course_search
Guest -> course_view
Guest -> authenticate
' ====================
Student --> course_search
Student -> course_view

Student -> enrollment_enroll
Student -> enrollment_search
Student -> enrollment_view
Student -> enrollment_drop

Student -> classroom_search
Student -> classroom_view

Student -> schedule_search
Student -> schedule_view
' ====================
Teacher --> course_search
Teacher -> course_view

Teacher -> enrollment_search
Teacher -> enrollment_view

Teacher -> classroom_search
Teacher -> classroom_view
Teacher -> classroom_administrate

Teacher -> schedule_search
Teacher -> schedule_view
Teacher -> schedule_administrate
' ====================
Admin --> course_search
Admin -> course_view

Admin -> enrollment_search
Admin -> enrollment_view

Admin -> classroom_search
Admin -> classroom_view
' ====================


note right of "Course"
    Permissions:
    - anyone can search/view courses
end note

note right of "Enrollment"
    Permissions:
    - students can only search/view/drop their personal enrollments
    - teachers can only search/view their course enrollments
    - admins can search/view/drop all enrollments
end note

note right of "Classroom"
    Permissions:
    - students can only search/view their classroom
    - teachers can only search/view/administrate their classroom
    - admins can search/view all classrooms
end note

note right of "Schedule"
    Permissions:
    - students can only search/view their schedule
    - teachers can only search/view/administrate their schedule
    - admins can search/view all schedules
end note

@enduml
